import axios from 'axios';
import type { AxiosInstance } from 'axios';
import type {
  Item,
  Category,
  Claim,
  ItemCreateInput,
  ItemUpdateInput,
  ClaimCreateInput,
} from '../types';

// API Base Configuration
const API_BASE_URL = 'http://localhost:3001';

const axiosInstance: AxiosInstance = axios.create({
  baseURL: API_BASE_URL,
  timeout: 10000,
  headers: {
    'Content-Type': 'application/json',
  },
});

// ==========================================
// ITEMS API
// ==========================================

/**
 * Fetch all items from json-server
 */
export const fetchItems = async (): Promise<Item[]> => {
  const response = await axiosInstance.get<Item[]>('/items');
  return response.data;
};

/**
 * Fetch a single item by ID
 */
export const fetchItemById = async (id: string): Promise<Item> => {
  const response = await axiosInstance.get<Item>(`/items/${id}`);
  return response.data;
};

/**
 * Create a new item (POST)
 * Accepts ItemCreateInput (which omits 'id' auto-generated by the backend)
 */
export const createItem = async (itemData: ItemCreateInput): Promise<Item> => {
  const response = await axiosInstance.post<Item>('/items', itemData);
  return response.data;
};

/**
 * Update an existing item (PUT/PATCH)
 */
export const updateItem = async (id: string, itemData: ItemUpdateInput): Promise<Item> => {
  const response = await axiosInstance.patch<Item>(`/items/${id}`, itemData);
  return response.data;
};

/**
 * Delete an item (DELETE)
 */
export const deleteItem = async (id: string): Promise<void> => {
  await axiosInstance.delete(`/items/${id}`);
};

// ==========================================
// CATEGORIES API
// ==========================================

/**
 * Fetch all item categories
 */
export const fetchCategories = async (): Promise<Category[]> => {
  const response = await axiosInstance.get<Category[]>('/categories');
  return response.data;
};

/**
 * Fetch a single category by ID
 */
export const fetchCategoryById = async (id: string): Promise<Category> => {
  const response = await axiosInstance.get<Category>(`/categories/${id}`);
  return response.data;
};

// ==========================================
// CLAIMS API
// ==========================================

/**
 * Fetch all claims
 */
export const fetchClaims = async (): Promise<Claim[]> => {
  const response = await axiosInstance.get<Claim[]>('/claims');
  return response.data;
};

/**
 * Fetch claims specifically for an item ID
 */
export const fetchClaimsByItemId = async (itemId: string): Promise<Claim[]> => {
  const response = await axiosInstance.get<Claim[]>('/claims', {
    params: { itemId },
  });
  return response.data;
};

/**
 * Create a new claim (POST)
 * Accepts ClaimCreateInput (which omits 'id' auto-generated by the backend)
 */
export const createClaim = async (claimData: ClaimCreateInput): Promise<Claim> => {
  const response = await axiosInstance.post<Claim>('/claims', claimData);
  return response.data;
};

/**
 * Update claim status
 */
export const updateClaimStatus = async (
  id: string,
  status: 'pending' | 'approved' | 'rejected'
): Promise<Claim> => {
  const response = await axiosInstance.patch<Claim>(`/claims/${id}`, { status });
  return response.data;
};

export default axiosInstance;
